Use click for command line options.
anirudhajith/process-wallpaper pull request #21
Opened 2019-08-31 07:52 UTC by dsluo

A quick implementation of using `click` to allow users to specify options using command line arguments. Not completely sure if `click` is the *best* option. Might simply want to use `argparse` for better flexibility.

2019-09-01 09:21 UTC, anirudhajith commented
@dsluo I see that you've done a lot of nice work. Please update `README.md` with usage and setup instructions.

2019-09-01 09:23 UTC, anirudhajith requested changes
@dsluo I see that you've done a lot of nice work. Please update `README.md` with usage and setup instructions.

2019-09-02 22:33 UTC, dsluo commented
Actually I'm gonna change a few things about how the arguments are handled. I'll reopen this once that is done.

2019-09-02 23:52 UTC, dsluo commented
On second thought, I'm going to make a separate issue for what i was thinking.

2026-01-10 00:36 UTC, closed without merging